"""
Contains the TranslationModel class.
"""

from typing import Optional, Annotated
from datetime import datetime
from pydantic import ConfigDict, BaseModel, Field
from pydantic.functional_validators import BeforeValidator

# Represents an ObjectId field in the database.
# It will be represented as a `str` on the model so that it can be serialized to JSON.
PyObjectId = Annotated[str, BeforeValidator(str)]


class PromptResponseModel(BaseModel):
    """
    Prompt-Response model that represents prompt asked by user and the response generated by the gemini model.
    """

    # The primary key for the StudentModel, stored as a `str` on the instance.
    # This will be aliased to `_id` when sent to MongoDB,
    # but provided as `id` in the API requests and responses.
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    prompt: str = Field(...)
    response: str = Field(...)
    created_at: Optional[datetime] = Field(default=None)

    model_config = ConfigDict(
        populate_by_name=True,
        arbitrary_types_allowed=False,
        json_schema_extra={
            "example": {
                "prompt": "What criteria should I fulfill to be considered a citizen of India?",
                "response": "Response returned by model"
            }
        },
    )


class GetPromptModel(BaseModel):
    """_summary_
    Get prompt Model
    """

    prompt: str = Field(...)
    model_config = ConfigDict(
        populate_by_name=True,
        arbitrary_types_allowed=False,
        json_schema_extra={
            "example": {
                "prompt": "What criteria should I fulfill to be considered a citizen of India?"
            }
        },
    )
