name: Constitution GPT CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: make .env file available
      run:  |
          cp /home/ubuntu/my-backend-constitution-gpt.env backend/.env
   

    - name: Stop existing docker compose container and delete images
      run: sudo docker compose -f docker-compose-prod.yaml down --rmi local
    - name: run the docker compose container on port 4000 and bye bye
      run: sudo docker compose -f docker-compose-prod.yaml up -d
